// Console Log Assignment

console.clear(); //clear console

console.log ('soup'); // string

console.log (2021); // integer

console.log (true); // boolean

var greetings = 'Good day' //variable
console.log (greetings);

let greetingsV2 = 'Have you eat your breakfast?'  //let
console.log (greetingsV2);

console.log ([1,2,3,4,5,6,7,8]); //array

console.log ({ten: 10, five: 5}); //object

console.table ({ten: 10, five: 5}); //table display object

console.error ('Error Detected'); //error message

console.warn('Warning!'); //warning message

console.time('Breakfast'); //logs time
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.log('soup');
console.timeEnd('soup'); 
© 2021 GitHub, Inc.
