//Primitive Type

const name = 'Aldrich'; //string
console.log(name);

const age = 32; //integer
console.log(age);

const hungry = true; //boolean
console.log(food);

const money = null; //null
console.log(money);

let dogname; //undefined
console.log(dogname);

const favFood = ['pizza, spaghetti, lazana']; //reference type - object 
console.log(favFood);

//Object literal
const address = {
    city: 'San Miguel',
    barangay: 'Buga',
    street: 'Purok 5'
}
console.log(address);

const time = new Date();
console.log(time);
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
