// single line comment

/*
multi line comments
*/

var name = 'Nivin Kody'; //variable
console.log(name);
name = 'Cava';
console.log(name);

var food; //initialize var undefined
console.log(food);
food = 'Spaghetti'; //defined var
console.log(food);

//acceptable var letters, numbers, _, $
//cannot start with a number

var firstName = 'Divine'; //camel cased *2nd word uppercase *SUGGESTED
var FirstName = 'Cava'; //pascal case *both uppercase
console.log (firstName);
console.log (FirstName);

let drink; //let
drink = 'Mango Juice';
console.log (drink);

const names = 'Violet'; //const can't reassign
console.log (name);

//const object *property can be changed
const person = {       
    name: 'Nivin',
    age: 29
};
console.log(person)

person.age = (19);
console.log(person)

const numbers = [1,2,4,5,6,7,8,9,0]; //const number array

numbers.push(38);
console.log(numbers);
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
